name: Test

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 20, 22]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run the tests
        run: npm run test:coverage

      - name: Submit coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          flags: integration
          token: ${{ secrets.CODECOV_TOKEN }}
# Note: test on Windows is impossible,
# because test assets become diff filenames with content hash,
# the same problem with node 14
